export { default as Navigation } from './Navigation'
export { default as Hero } from './Hero'
export { default as WhatWeDo } from './WhatWeDo'
export { default as WhySprintly } from './WhySprintly'
export { default as HowItWorks } from './HowItWorks'
export { default as Testimonials } from './Testimonials'
export { default as CTASection } from './CTASection'
export { default as Footer } from './Footer'